### ISSUE TITLE
Unable to start server.py on Windows -- reports No module named deoplete_jedi

### ISSUE THREAD

**Issue by arkottke** [zchee/deoplete-jedi#107]
# Problem summary

`deoplete_jedi\server.py` reports `No module named 'deoplete_jedi'`.

This error can be fixed by inserting the appropriate relative paths in `server.py`, but this seems like the wrong solution.

## Expected

No error when loading "server.py"

## Environment Information

 * OS: Windows 7
 * Neovim version: v0.2.0-625-gbeb2ef46

## Provide a minimal init.vim with less than 50 lines (required)

```vim
execute pathogen#infect()
syntax on
filetype plugin indent on

set runtimepath+=~/Documents/GitHub/dotfiles/neovim/bundle/deoplete/
set runtimepath+=~/Documents/GitHub/dotfiles/neovim/bundle/deoplete-jedi/

let g:deoplete#enable_at_startup = 1
call deoplete#custom#set('jedi', 'debug_enabled', 1)
call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
```
Need to load pathogen.

## Generate logfiles if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/nvim-log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc

Then look at and attach the files `/tmp/nvim-log_{PID}` and
`/tmp/deoplete.log` here.

### deoplete.log
```
2017-02-16 16:19:25,274 INFO     (deoplete.logging) --- Deoplete Log Start ---
2017-02-16 16:19:25,321 INFO     (deoplete.logging) NVIM v0.2.0-625-gbeb2ef46, Python 3.6.0, neovim client 0.1.13
```

### Messages
```
[deoplete] Logging to /tmp/deoplete.log
Warning: Font "Fira Code" reports bad fixed pitch metrics
"~\Desktop\calc_elo.py" 35L, 1143C
[deoplete] Error when loading source jedi: Failed to start server (python -u C:\Users\akottke\AppData\Local\nvim\bundle\deoplete-jedi\rplugin/python3/deoplete\sources\deoplete_jedi\server.py --desc-length 0 --debug  --debug-level 10): Server exited with b'Traceback (most recent call last):\r\n  File "C:\\Users\\akottke\\AppData\\Local\\nvim\\bundle\\deoplete-jedi\\rplugin/python3/deoplete\\sources\\deoplete_jedi\\server.py", line 26, in <module>\r\n    from deoplete_jedi import utils\r\nModuleNotFoundError: No module named \'deoplete_jedi\'\r\n': error: 1. Ignoring.
[deoplete] Error when loading source jedi: Failed to start server (python -u C:\Users\akottke\AppData\Local\nvim\bundle\deoplete-jedi\rplugin/python3/deoplete\sources\deoplete_jedi\server.py --desc-length 0 --debug  --debug-level 10): Server exited with b'Traceback (most recent call last):\r\n  File "C:\\Users\\akottke\\AppData\\Local\\nvim\\bundle\\deoplete-jedi\\rplugin/python3/deoplete\\sources\\deoplete_jedi\\server.py", line 26, in <module>\r\n    from deoplete_jedi import utils\r\nModuleNotFoundError: No module named \'deoplete_jedi\'\r\n': error: 1. Ignoring.
[deoplete] Traceback (most recent call last):
[deoplete]   File "C:\Users\akottke\AppData\Local\nvim\bundle\deoplete-jedi\rplugin/python3/deoplete\sources\deoplete_jedi\server.py", line 518, in restart
[deoplete]     self.version = stream_read(self._server.stdout)
[deoplete]   File "C:\Users\akottke\AppData\Local\nvim\bundle\deoplete-jedi\rplugin/python3/deoplete\sources\deoplete_jedi\server.py", line 87, in stream_read
[deoplete]     raise StreamEmpty
[deoplete] deoplete_jedi.server.StreamEmpty
[deoplete] 
[deoplete] During handling of the above exception, another exception occurred:
[deoplete] 
[deoplete] Traceback (most recent call last):
[deoplete]   File "C:\Users\akottke\AppData\Local\nvim\bundle\deoplete-jedi\rplugin/python3/deoplete\sources\deoplete_jedi\server.py", line 493, in __init__
[deoplete]     self.restart()
[deoplete]   File "C:\Users\akottke\AppData\Local\nvim\bundle\deoplete-jedi\rplugin/python3/deoplete\sources\deoplete_jedi\server.py", line 522, in restart
[deoplete]     err, self._server.returncode))
[deoplete] Exception: Server exited with b'Traceback (most recent call last):\r\n  File "C:\\Users\\akottke\\AppData\\Local\\nvim\\bundle\\deoplete-jedi\\rplugin/python3/deoplete\\sources\\deoplete_jedi\\server.py", line 26, in <module>\r\n    from deoplete_jedi import utils\r\nModuleNotFoundError: No module named \'deoplete_jedi\'\r\n': error: 1
[deoplete] 
[deoplete] During handling of the above exception, another exception occurred:
[deoplete] 

[deoplete] Traceback (most recent call last):
[deoplete]   File "C:/Users/akottke/AppData/Local/nvim/bundle/deoplete/rplugin/python3\deoplete\deoplete.py", line 206, in itersource
[deoplete]     source.on_init(context)
[deoplete]   File "C:\Users\akottke/Documents/GitHub/dotfiles/neovim/bundle/deoplete-jedi/rplugin/python3/deoplete\sources\deoplete_jedi.py", line 80, in on_init
```

## Steps to reproduce the issue after starting Neovim (required)

 1. Open .py file.

## Screen shot (if possible)

![image](https://cloud.githubusercontent.com/assets/1033651/23047365/361a78f0-f464-11e6-9612-48fc8630ca2c.png)

**Comment by tweekmonster** [comment]
I haven't tested this with Python 3.6, let alone Windows.  All I can say is that this looks like the `PYTHONPATH` environment variable isn't seen by the server.

You could try adding:

```python
log.debug('XXX ENV: %r', self.env)
```

on this line: https://github.com/zchee/deoplete-jedi/blob/6240de812f06263524f46379ad08a0d3d539730f/rplugin/python3/deoplete/sources/deoplete_jedi/server.py#L491

Then post the emitted message that's in the log file.

Side note: Does this need to use `C:\whatever` on Windows?

```vim
call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
```

**Comment by arkottke** [comment]
Here is the output of `self.env`:
```
2017-02-17 07:48:42,553 INFO     (deoplete.logging) --- Deoplete Log Start ---
2017-02-17 07:48:42,585 INFO     (deoplete.logging) NVIM v0.2.0-625-gbeb2ef46, Python 3.6.0, neovim client 0.1.13
2017-02-17 07:48:53,213 DEBUG    (deoplete.jedi.client) XXX ENV: {'ALLUSERSPROFILE': 'C:\\ProgramData', 'APPDATA': 'C:\\Users\\akottke\\AppData\\Roaming', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'COMPUTERNAME': 'SFBD29905', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'FLEXLM_TIMEOUT': '200000000', 'FP_NO_HOST_CHECK': 'NO', 'GDAL_DATA': 'C:\\Program Files\\PostgreSQL\\9.5\\gdal-data', 'GEOSERVER_DATA_DIR': 'C:\\Program Files (x86)\\GeoServer 2.8.2\\data_dir', 'HOME': 'C:\\Users\\akottke', 'HOMEDRIVE': 'M:', 'HOMEPATH': '\\', 'HOMESHARE': '\\\\asbf54040\\users$', 'HTTPS_PROXY': 'https://localhost:3128', 'HTTP_PROXY': 'http://localhost:3128', 'JAVA_HOME': 'C:\\Program Files (x86)\\Java\\jre1.8.0_45', 'LOCALAPPDATA': 'C:\\Users\\akottke\\AppData\\Local', 'LOGONSERVER': '\\\\CHIS-AMERS1', 'MOZ_PLUGIN_PATH': 'C:\\Program Files (x86)\\Nuance\\Power PDF\\Bin\\', 'MYVIMRC': 'C:\\Users\\akottke\\AppData\\Local\\nvim\\init.vim', 'NUMBER_OF_PROCESSORS': '4', 'NVIM_LISTEN_ADDRESS': '\\\\.\\pipe\\nvim-26508-0', 'ONEDRIVE': 'C:\\Users\\akottke\\OneDrive - Bechtel Corporation', 'OS': 'Windows_NT', 'PATH': 'C:\\Users\\akottke\\AppData\\Local\\Continuum\\Miniconda3\\Library\\bin;C:\\Program Files\\Common Files\\Microsoft Shared\\Windows Live;C:\\Program Files (x86)\\Common Files\\Microsoft Shared\\Windows Live;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Program Files\\SafeNet\\Authentication\\SAC\\x32;C:\\Program Files\\SafeNet\\Authentication\\SAC\\x64;C:\\Program Files (x86)\\Java\\jre7\\bin;C:\\Program Files (x86)\\Microsoft Application Virtualization Client;C:\\Program Files (x86)\\Unrar;c:\\Program Files (x86)\\MATLAB\\MATLAB Compiler Runtime\\v714\\runtime\\win32;C:\\Program Files\\MATLAB\\MATLAB Compiler Runtime\\v82\\runtime\\win64;C:\\Program Files (x86)\\MATLAB\\MATLAB Compiler Runtime\\v82\\runtime\\win32;C:\\Program Files (x86)\\SysinternalsSuite;C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin;C:\\Program Files\\gs\\gs9.19\\bin;C:\\Program Files (x86)\\GnuWin32\\bin;C:\\Program Files (x86)\\Windows Live\\Shared;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Strawberry\\c\\bin;C:\\Strawberry\\perl\\site\\bin;C:\\Strawberry\\perl\\bin;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Users\\akottke\\AppData\\Local\\Programs\\Python\\Launcher\\;C:\\Users\\akottke\\AppData\\Local\\Continuum\\Miniconda3;C:\\Users\\akottke\\AppData\\Local\\Continuum\\Miniconda3\\Scripts;C:\\Users\\akottke\\AppData\\Local\\Continuum\\Miniconda3\\Library\\bin;C:\\Users\\akottke\\Documents\\bin;C:\\Program Files\\mupdf;C:\\devel\\nvim\\bin', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'POSTGIS_ENABLE_OUTDB_RASTERS': '1', 'POSTGIS_GDAL_ENABLED_DRIVERS': 'GTiff PNG JPEG GIF XYZ DTED USGSDEM AAIGrid', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel', 'PROCESSOR_LEVEL': '6', 'PROCESSOR_REVISION': '3a09', 'PROGRAMDATA': 'C:\\ProgramData', 'PROGRAMFILES': 'C:\\Program Files', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'PROGRAMW6432': 'C:\\Program Files', 'PROMPT': '$p$_$+$g', 'PSMODULEPATH': 'C:\\Users\\akottke\\Documents\\WindowsPowerShell\\Modules', 'PUBLIC': 'C:\\Users\\Public', 'SESSIONNAME': 'Console', 'SYSTEMDRIVE': 'C:', 'SYSTEMROOT': 'C:\\Windows', 'TEMP': 'c:\\temp', 'TESSDATA_PREFIX': 'C:\\Program Files (x86)\\Tesseract-OCR\\', 'TMP': 'c:\\temp', 'UATDATA': 'C:\\Windows\\CCM\\UATData\\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77', 'USERDNSDOMAIN': 'AMERS.IBECHTEL.COM', 'USERDOMAIN': 'IAMERS', 'USERNAME': 'akottke', 'USERPROFILE': 'C:\\Users\\akottke', 'VIM': 'C:\\devel\\nvim\\share\\nvim', 'VIMRUNTIME': 'C:\\devel\\nvim\\share\\nvim\\runtime', 'VS140COMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\', 'WINDIR': 'C:\\Windows', 'PYTHONPATH': 'C:\\Users\\akottke\\AppData\\Local\\nvim\\bundle\\deoplete-jedi\\rplugin/python3/deoplete\\jedi:C:\\Users\\akottke\\AppData\\Local\\nvim\\bundle\\deoplete-jedi\\rplugin/python3/deoplete\\sources'}
```
It looks like the `PYTHONPATH` is being joined by `:` instead of `;`.

**Comment by tweekmonster** [comment]
Good catch!
