### ISSUE TITLE
AttributeError in Python 3.6

### ISSUE THREAD

**Issue by sphaugh** [zchee/deoplete-jedi#143]
# Problem summary

Python 3.6.3 generates `AttributeError` here:
```python
        if self.debug_server is not None and self.debug_server:
            self.is_debug_enabled = True
            if isinstance(self.debug_server, str):
                log_file = self.debug_server
            else:
                for handler in root_log.handlers:
                    if isinstance(handler, logging.FileHandler):
                        log_file = handler.baseFilename
                        break


        if not self.is_debug_enabled:
            child_log = root_log.getChild('jedi')
            child_log.propagate = False
```
```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/sean/etc/nvim/.config/nvim/plug/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 306, in itersource
[deoplete]     source.on_init(context)                                                                                               
[deoplete]   File "/home/sean/.config/nvim/plug/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 73, in on_init
[deoplete]     if not self.is_debug_enabled:                                                                                         
[deoplete] AttributeError: 'Source' object has no attribute 'is_debug_enabled'
[deoplete] Error when loading source jedi: 'Source' object has no attribute 'is_debug_enabled'. Ignoring..  Use :messages for error deta
ils.
```

**Comment by Shougo** [comment]
I cannot reproduce the problem.
I think your deoplete is too old.
Please update deoplete to the latest version.

**Comment by sphaugh** [comment]
Updating solved my issue. Thanks!

**Comment by Shougo** [comment]
OK.
