### ISSUE TITLE
wrong column when complete in a line with CJK font

### ISSUE THREAD

**Issue by JoveYu** [zchee/deoplete-jedi#196]
# Problem summary
completions in a line with CJK font, raise a ValueError 
mayby pass wrong column to jedi, through wrong encoding

example
```
class A:
    def __init__(self, cjk='', other=''):
        pass

class B:
    a = A(cjk='你好',ot<here>)
```

traceback
```
[deoplete] Traceback (most recent call last):
  File "/Users/jove/.cache/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/child.py", line 220, in _gather_results
    ctx['candidates'] = source.gather_candidates(ctx)
  File "/Users/jove/.cache/dein/repos/github.com/zchee/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/jove/.cache/dein/repos/github.com/zchee/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 171, in gather_candidates
    environment=self._env)
  File "/Users/jove/.cache/dein/repos/github.com/zchee/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/jove/.cache/dein/repos/github.com/zchee/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 125, in get_script
    return jedi.Script(source, line, col, filename, environment=self._env)
  File "/Users/jove/.cache/dein/repos/github.com/zchee/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/__init__.py", line 138, in __init__
    column, line_len, line, line_string))
ValueError: `column` parameter (23) is not in a valid range (0-22) for line 8 ("    a = A(cjk='你好',ot)\n").
Error from jedi: ValueError('`column` parameter (23) is not in a valid range (0-22) for line 8 ("    a = A(cjk=\'你好\',ot)\\n").').  Use :messages / see above for error details.
```

## Expected
no exception

## Environment Information

 * OS: macos
 * Neovim version: v0.3.1

## Provide a minimal init.vim with less than 50 lines (required)

cat `init.vim`
```vim
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/deoplete.nvim/
set runtimepath+=~/.cache/dein/repos/github.com/zchee/deoplete-jedi/
let g:deoplete#enable_at_startup = 1
call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
```

## Generate logfiles if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/nvim-log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc

Then look at and attach the files `/tmp/nvim-log_{PID}` and
`/tmp/deoplete.log` here.

## Upload the logfile(s)
[deoplete.log](https://github.com/zchee/deoplete-jedi/files/2387859/deoplete.log)
[nvim-log_py3_rplugin.log](https://github.com/zchee/deoplete-jedi/files/2387863/nvim-log_py3_rplugin.log)

**Comment by Shougo** [comment]
Please test https://github.com/zchee/deoplete-jedi/pull/197.

**Comment by JoveYu** [comment]
good job, work well

**Comment by Shougo** [comment]
OK.  I will merge it later.
