### ISSUE TITLE
deoplete-jedi fails a lot recently

### ISSUE THREAD

**Issue by plague-doctor** [zchee/deoplete-jedi#206]
# Problem summary

Deoplete-jedi started to fail a lot for me recently. I am unable to pin down the exact date when it started (had a month long brake from coding) but it is very frustrating.

```
[deoplete] Traceback (most recent call last):                                                   
  File "/home/me/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 43, in filter_names                                                
    k = (new.name, new.complete)  # key                                                          
  File "/home/me/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/classes.py", line 434, in complete                                                      
    return self._complete(True)                                                                  
  File "/home/me/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/classes.py", line 403, in _complete                                                     
    if self._name.api_type == 'param' and self._stack is not None:                               
  File "/home/me/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/evaluate/compiled/context.py", line 237, in api_type                                        
    return next(iter(self.infer())).api_type                                                     
StopIteration                                                                                    
The above exception was the direct cause of the following exception:                             
Traceback (most recent call last):                                                               
  File "/home/me/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 179, in _gather_results                                                                        
    result = self._get_result(context, source)                                                   
  File "/home/me/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 234, in _get_result                                                                            
    ctx['candidates'] = source.gather_candidates(ctx)                                            
  File "/home/me/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper                                                        
    return func(self, *args, **kwargs)                                                           
  File "/home/me/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 170, in gather_candidates                                                      
    completions = self.get_completions(script)                                                   
  File "/home/me/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper                                                        
    return func(self, *args, **kwargs)                                                           
  File "/home/me/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 123, in get_completions                                                        
    return script.completions()                                                                  
  File "/home/me/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/__init__.py", line 179, in completions                                                  
    completions = completion.completions()                                                       
  File "/home/me/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/vendored/jedi/jedi/api/completion.py", line 103, in completions                                                
    return sorted(completions, key=lambda x: (x.name.startswith('__'),                           
RuntimeError: generator raised StopIteration                                                     
Error from jedi: RuntimeError('generator raised StopIteration').  Use :messages / see above for e
rror details.
```

## Environment Information

 * OS: Arch
 * Neovim version: 0.3.1

I have updated the python-jedi (ver: 0.13.1) both from community repo and with pip.

Not sure what else I could try...

**Comment by plague-doctor** [comment]
It looks like this is very similar (same?) to [issue-1236](https://github.com/davidhalter/jedi/issues/1236)

**Comment by Shougo** [comment]
I know the problem....
I will add the flag to ignore the errors.

**Comment by Shougo** [comment]
Please use `let g:deoplete#sources#jedi#ignore_errors = v:true`.
