### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by Alok** [zchee/deoplete-jedi#26]
# Problems summary

I sometimes get the following error when typing in a python file.

## Environment Information

 * OS: OSX 10.11.4
 * Neovim version: latest build from git

## Traceback

```
[deoplete] An error has occurred. Please execute :messages command.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/alokbeniwal/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 47, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/Users/alokbeniwal/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 85, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/Users/alokbeniwal/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 150, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "/Users/alokbeniwal/.config/nvim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 321, in gather_candidates
[deoplete]     name, type_, desc, abbr = self.parse_completion(c, tmp_filecache)
[deoplete]   File "/Users/alokbeniwal/.config/nvim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 202, in parse_completion
[deoplete]     line = lines[i].lstrip()
[deoplete] IndexError: list index out of range
```

**Comment by yevhen-m** [comment]
I have the same error.

**Comment by zchee** [comment]
@Alok @yevhen-m Thanks issue :)

Maybe, It solved this PR https://github.com/zchee/deoplete-jedi/pull/25
Could you test it?

**Comment by zchee** [comment]
missed

**Comment by yevhen-m** [comment]
@zchee I pulled it. I don't know the steps to reproduce this error. Can you help with that?

**Comment by yevhen-m** [comment]
I'm using PR #25 revision and error is still there.

**Comment by tweekmonster** [comment]
@yevhen-m I pushed another change to that PR.  Could you see if that fixes it?  I'm having a hard time reproducing it.  As far as I can see, this shouldn't even be a possible 😕

**Comment by yevhen-m** [comment]
OK, I've pulled your revision.

**Comment by zchee** [comment]
Not reply. Close.

If you stil. occur error, Please reopen the issue.

**Comment by Alok** [comment]
Oh sorry, I forgot to comment that it's fixed now. Thanks.

**Comment by zchee** [comment]
@Alok np!
