### ISSUE TITLE
Completion of pymongo (python MongoDB driver) throws error

### ISSUE THREAD

**Issue by intelliHugh** [zchee/deoplete-jedi#41]
# Problems summary
Completion candidates from the [pymongo](https://github.com/mongodb/mongo-python-driver) package throw errors.

## Environment Information

 * OS: Ubuntu 14.04 Trusty
 * Neovim version: 0.1.5-dev

## Provide a minimal init.vim with less than 50 lines (Required!)

I've tried with this suggested minimal init.vim and the problem occurs
```vim
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
set runtimepath+=~/path/to/deoplete-jedi/
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)

 1. Open a python file (maybe a new one)
 2. Import pymongo: `import pymongo`
 3. Use the package in some way: `pymongo.MongoClient()`

While `pymongo` is being entered in point 3 a completion is available as expected:
![image](https://cloud.githubusercontent.com/assets/13149429/15712355/f2bc0456-2809-11e6-945e-b8c9726c6f11.png)
But there is no completion when typing `MongoClient`:
![image](https://cloud.githubusercontent.com/assets/13149429/15712380/0aa0827c-280a-11e6-8e73-0a25cede91a3.png)
When I look at the `:messages`, there is a string of errors:
![image](https://cloud.githubusercontent.com/assets/13149429/15712414/2bd90a7c-280a-11e6-93a9-17cefa9f48a6.png)

The full error message repeats as the completion is requested, the complete stack trace is:
```
[deoplete] An error has occurred. Please execute :messages command.                                                                                                                                                                   
[deoplete] Traceback (most recent call last):                                                                                                                                                                                         
[deoplete]   File "/home/mcnamara/.config/nvim/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 47, in completion_begin                                                                         
[deoplete]     complete_position, candidates = self.gather_candidates(context)                                                                                                                                                        
[deoplete]   File "/home/mcnamara/.config/nvim/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 81, in gather_candidates                                                                        
[deoplete]     results = self.gather_results(context)                                                                                                                                                                                 
[deoplete]   File "/home/mcnamara/.config/nvim/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 132, in gather_results                                                                          
[deoplete]     context['candidates'] = source.gather_candidates(context)                                                                                                                                                              
[deoplete]   File "/home/mcnamara/.config/nvim/dein/repos/github.com/zchee/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper                                                             
[deoplete]     return func(self, *args, **kwargs)                                                                                                                                                                                     
[deoplete]   File "/home/mcnamara/.config/nvim/dein/repos/github.com/zchee/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 113, in gather_candidates                                                           
[deoplete]     for filename, mtime in modules.items()]):                                                                                                                                                                              
[deoplete]   File "/home/mcnamara/.config/nvim/dein/repos/github.com/zchee/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 113, in <listcomp>                                                                  
[deoplete]     for filename, mtime in modules.items()]):                                                                                                                                                                              
[deoplete]   File "/home/mcnamara/anaconda3/lib/python3.5/genericpath.py", line 55, in getmtime                                                                                                                                       
[deoplete]     return os.stat(filename).st_mtime                                                                                                                                                                                      
[deoplete] FileNotFoundError: [Errno 2] No such file or directory: '/home/<user>/.hugh/test.py'                                                                                                                                     
[deoplete] An error has occurred. Please execute :messages command.   
```

**Comment by tweekmonster** [comment]
Have you updated recently?  The line numbers in the error don't match up with past few commits.

**Comment by intelliHugh** [comment]
@tweekmonster: that solved it, thanks.
