### ISSUE TITLE
deoplete_jedi.server.StreamEmpty

### ISSUE THREAD

**Issue by sungminoh** [zchee/deoplete-jedi#51]
# Problems summary

When editing python files, deoplete_jedi raises StreamEmpty error

I installed neovim through Homebrew
python neovim plugins were installed successuflly through pip2 and pip3

## Environment Information

 * OS: OSX 10.11.6
 * Neovim version: 0.1.4

## Provide a minimal init.vim with less than 50 lines (Required!)

let g:python_host_prog = '/usr/local/bin/python'
let g:python3_host_prog = '/usr/local/bin/python3'
let g:deoplete#enable_at_startup = 1

## The reproduce ways from neovim starting (Required!)

 1. nvim a.py
 2. type anything
-> error occurs

## Screen shot (if possible)

![screenshot_05](https://cloud.githubusercontent.com/assets/11041693/17505052/3d8b1282-5e39-11e6-8900-5071602a15d0.png)

**Comment by tweekmonster** [comment]
That means that the server failed to start.  Try setting `deoplete#sources#jedi#python_path` to a Python path and see if that fixes it.

**Comment by ludbek** [comment]
I am getting the same error.

**Comment by tweekmonster** [comment]
You may need to upgrade Deoplete.

**Comment by ludbek** [comment]
Deoplete is already up to date.

**Comment by tweekmonster** [comment]
Did you guys install this by cloning the repo?  If so, you will need to run: `git submodule update --init` in the repo directory.

**Comment by ludbek** [comment]
I used vim-plug to install it. It works fine in my work machine but wont work at home. There is also the possibility of improper configuration on my part. Also running `git submodule update --init` displayed nth, it silently exists.

**Comment by zchee** [comment]
@ludbek Oh, wait. Are you saw the error message at line 3~6?
It means `Please disable ~/.dotfiles/vim/plugged/SimpyIFold/ftplugin/python/SimpyIFold.vim or insall FastFold plugin`.

Do you try it? If no, could you check it?

**Comment by ludbek** [comment]
I get following error.

```
[deoplete] Traceback (most recent call last):                                                                          
[deoplete] Traceback (most recent call last):                                                                          
[deoplete] Traceback (most recent call last):                                                                          
[deoplete]   File "/home/user/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 272, in
 load_sources                                                                                                          
[deoplete]   File "/home/user/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 272, in
 load_sources                                                                                                          
[deoplete]   File "/home/user/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 272, in
 load_sources                                                                                                          
[deoplete]     source.on_init(context)                                                                                 
[deoplete]     source.on_init(context)                                                                                 
[deoplete]     source.on_init(context)                                                                                 
[deoplete]   File "/home/user/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py",
 line 66, in on_init                                                                                                   
[deoplete]   File "/home/user/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py",
 line 66, in on_init                                                                                                   
[deoplete]   File "/home/user/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py",
 line 66, in on_init                                                                                                   
[deoplete]     self.debug_enabled, self.python_path)                                                                   
[deoplete]     self.debug_enabled, self.python_path)                                                                   
[deoplete]     self.debug_enabled, self.python_path)                                                                   
[deoplete]   File "/home/user/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/work
er.py", line 81, in start                                                                                              
[deoplete]   File "/home/user/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/work
er.py", line 81, in start                                                                                              
[deoplete]   File "/home/user/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/work
er.py", line 81, in start                                                                                              
[deoplete]     show_docstring, debug, python_path)                                                                     
[deoplete]     show_docstring, debug, python_path)                                                                     
[deoplete]     show_docstring, debug, python_path)                                                                     
[deoplete]   File "/home/user/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/work
er.py", line 24, in __init__                                                                                           
[deoplete]   File "/home/user/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/work
er.py", line 24, in __init__                                                                                           
[deoplete]   File "/home/user/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/work
er.py", line 24, in __init__                                                                                           
[deoplete]     python_path)                                                                                            
[deoplete]     python_path)                                                                                            
[deoplete]     python_path)                                                                                            
[deoplete]   File "/home/user/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/serv
er.py", line 502, in __init__                                                                                          
[deoplete]   File "/home/user/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/serv
er.py", line 502, in __init__                                                                                          
[deoplete]   File "/home/user/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/serv
er.py", line 502, in __init__                                                                                          
[deoplete]     self.restart()                                                                                          
[deoplete]     self.restart()                                                                                          
[deoplete]     self.restart()                                                                                          
[deoplete]   File "/home/user/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/serv
er.py", line 518, in restart                                                                                           
[deoplete]   File "/home/user/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/serv
er.py", line 518, in restart                                                                                           
[deoplete]   File "/home/user/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/serv
er.py", line 518, in restart                                                                                           
[deoplete]     self.version = stream_read(self._server.stdout)                                                         
[deoplete]     self.version = stream_read(self._server.stdout)                                                         
[deoplete]     self.version = stream_read(self._server.stdout)                                                         
[deoplete]   File "/home/user/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/serv
er.py", line 83, in stream_read                                                                                        
[deoplete]   File "/home/user/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/serv
er.py", line 83, in stream_read                                                                                        
[deoplete]   File "/home/user/.config/nvim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/serv
er.py", line 83, in stream_read                                                                                        
[deoplete]     raise StreamEmpty                                                                                       
[deoplete]     raise StreamEmpty                                                                                       
```

**Comment by Shougo** [comment]
@ludbek You may need to reinstall deoplete-jedi.

**Comment by ludbek** [comment]
@Shougo problem persists. I am in Ubuntu 16 (deoplete-jedi fails) and my work box is running Ubuntu 14(deoplete-jedi works) if that is any help.

**Comment by Shougo** [comment]
I have tested it in Ubuntu 16.04 and it worked.
neovim ver.0.1.4 is old.  You should build it manually.

**Comment by sungminoh** [comment]
I've found the cause of my case.
In my case, the problem was locale setting.
These are my previous lacale setting

LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=

However, 'UTF-8' for LC_CTYPE is actually not a proper locale. (there is no code 'UTF-8' for locale setting)
I couldn't figure out why it is set as such a weird code, but the error messages have gone after setting LC_CTYPE as 'en_US.UTF-8' (a proper one).
I think there is no exception handling regarding locale setting in deoplete-jedi.

@ludbek  I hope this solution works for you.

**Comment by ludbek** [comment]
@sungminoh Are those VIM settings?

**Comment by sungminoh** [comment]
@ludbek nope. It is global shell setting.
I'm using zsh, so I add
`export` LC_CTYPE="en_US.UTF-8"
in my zsh profile
